class BrainApp:
    @staticmethod
    async def new(config: dict) -> BrainApp: ...
    async def get_fields_by_dataset(self, dataset_name: str) -> list: ...
    async def simulation(self, dataset_name: str, alphas: list) -> None: ...
